### ISSUE TITLE
A Debian problem

### ISSUE THREAD

**Issue by jsbien** [FriedrichFroebel/didjvu#2]
I wanted to give your version a try, but got 
`No module named PIL; please install the python-pil package`
I'm on Debian, so I installed a package which seems appropriate, i.e. 
`python3-pypillowfight`, but it not helped. `pip install python-pil` and `pip install python3-pil` also doesn't work. (I'm not a programmer, so I work by trial and error).

**Comment by FriedrichFroebel** [comment]
You should either use `sudo apt-get install python3-pil` or `sudo python3 -m pip install Pillow` (the second variant might not need *sudo*, depending on your Python setup).

**Comment by jsbien** [comment]
The problem is more subtle...
`jsbien@JSBbuster:~/work/didjvu/Froebel/didjvu$ python3 -m pip install Pillow`
`Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (8.1.2)`
`jsbien@JSBbuster:~/work/didjvu/Froebel/didjvu$ sudo apt-get install python3-pil`
...
`python3-pil is already the newest version (8.1.2+dfsg-0.3)`.
Let me include the whole error message:
`jsbien@JSBbuster:~/work/didjvu/Froebel/didjvu$ ./didjvu `
`Traceback (most recent call last):`
 ` File "./didjvu", line 23, in <module>`
 `   from lib import didjvu`
 ` File "/home/jsbien/work/didjvu/Froebel/didjvu/lib/didjvu.py", line 31, in <module>`
    `from . import gamera_support as gamera`
 `File "/home/jsbien/work/didjvu/Froebel/didjvu/lib/gamera_support.py", line 27, in <module>`
   ` from PIL import Image as PIL`
`ImportError: No module named PIL; please install the python-pil package`
When installing a package the package python-is-python2 has been installed as a prerequisite. Can it be the culprit?

**Comment by FriedrichFroebel** [comment]
It seems like you are still using the old version. Please make sure that you are on the Python 3 branch: `git checkout python3`. Then try again.

**Comment by FriedrichFroebel** [comment]
Yes, you would most likely have to install it system-wide. An alternative is to use a virtual environment to encapsulate *didjvu* and its dependencies and install *gamera* there (this is what I did during migration), but this probably depends on your personal taste and experience as it requires some additional steps to set it up.

**Comment by jsbien** [comment]
Thanks!
