### ISSUE TITLE
Actions separate and encode are disfuncted

### ISSUE THREAD

**Issue by velwant** [FriedrichFroebel/didjvu#21]
I was used didjvu separate action in my djvutool, but version for Python3 get empty output stream. Action bundle is ok.

**Comment by FriedrichFroebel** [comment]
Sorry for the inconvenience - I am only using the `bundle` action myself. Unfortunately, the `didjvu.didjvu` module has never actually been tested, thus such issues currently stay invisible.

For now, I do not know when I find some more time to dig into this. Nevertheless, feel free to analyze it yourself and comment your findings or submit a corresponding pull request with a fix to resolve this.

**Comment by FriedrichFroebel** [comment]
I think I could locate the bug and fix it. Could you please verify that using the current *python3* branch or applying https://github.com/FriedrichFroebel/didjvu/commit/ce4f71947593dcc7d4e62154de969ec695ea9e59 to your code does indeed fix this?

**Comment by velwant** [comment]
Yes! This patch solved it. Thank you very much! Good work. I use very intensively mainly own bash shell script [djvutool](https://github.com/velwant/djvutool), which do seperated layers by use netpbm tools, but sometime is need use a specially algorithm for separation and uses didjvu for it.
I found out that the tools I use have been dropped from newer versions of debian because they lacked a maintaner, so I work do new build scripts. See https://salsa.debian.org/want

**Comment by FriedrichFroebel** [comment]
Thanks for checking. I published a corresponding release with this fix now.
