### ISSUE TITLE
 cannot import name 'cli' from partially initialized module 'didjvu'

### ISSUE THREAD

**Issue by jsbien** [FriedrichFroebel/didjvu#32]
On Debian stable I get 

python3 ~/work/didjvu/Froebel_new1/didjvu/didjvu/didjvu.py bundle *.jpg -o PT_XII_Crispa.djvu
Traceback (most recent call last):
  File "/home/jsbien/work/didjvu/Froebel_new1/didjvu/didjvu/didjvu.py", line 25, in <module>
    from didjvu import cli
  File "/home/jsbien/work/didjvu/Froebel_new1/didjvu/didjvu/didjvu.py", line 25, in <module>
    from didjvu import cli
ImportError: cannot import name 'cli' from partially initialized module 'didjvu' (most likely due to a circular import) (/home/jsbien/work/didjvu/Froebel_new1/didjvu/didjvu/didjvu.py)

I will appreciate your help.

**Comment by FriedrichFroebel** [comment]
Do not run the `didjvu.didjvu` module from the terminal. Just use `python3 -m didjvu` instead from the root of the repository.

**Comment by jsbien** [comment]
Thanks!
