### ISSUE TITLE
Remove numpy fix

### ISSUE THREAD

**Issue by rmast** [FriedrichFroebel/didjvu#7]
Friedrich,

In an ancient time @jwilk made this commit https://github.com/jwilk/didjvu/commit/78fbbcfe84b1254392d16b1ea368cc8a173c7a7a to 

didjvu (0.2.2) unstable; urgency=low

  * Prevent Numpy from being imported by Gamera (loading it takes noticeable
    amount of time, even though it's never needed).

In the now called gamera_support.py concerning the line 
```
lib/gamera_support.py:    sys.modules['numpy'] = None
```

I'm working on a PDF-compressor for OCRmyPDF making use of some didjvu-libraries with quite good results, for the moment pointing to your python3-branch.
I don't know if the fix still applies for Python2.7, but I don't see any speeddifference when I comment it out in the Python3-version. Can you remove that line?

**Comment by FriedrichFroebel** [comment]
In theory we do not need *numpy* within *didjvu*, so I do not see any reason for removing this line. *numpy* is used by some code from *gamera* which we obviously do not need/call, *Boost.Python* includes some *numpy*-related source files as well. Nevertheless, in CI *numpy* is never being installed as a Python library and apparently not required at all:

```
$ pip freeze
coverage==6.4.1
docutils==0.18.1
gamera==4.0.0
nose==1.3.7
Pillow==9.1.1
py3exiv2==0.11.0
pycairo==1.21.0
Pygments==2.12.0
PyGObject==3.42.1
python-xmp-toolkit==2.0.1
pytz==2022.1
```

What is the rationale behind your proposal? Do you even have *numpy* installed when testing for speed differences? Judging from my experience with larger projects incorporating *numpy*, not loading it when it is not required usually improves the memory footprint of the application (as the corresponding *.so* files do not have to loaded into memory).

**Comment by rmast** [comment]
My PDF compressor uses numpy, and that line causes a hard to solve error when I involve didjvu-libraries. If you're interested you might look at it in my new repo. You might be able to suggest another solution. Input should be an uncompressed OCRmyPDF containing hocr.

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by FriedrichFroebel** [comment]
For me it seems like your use-case is quite special and does not reflect the general usage patterns. Thinking about it, the easiest solution might be to add a `prevent_loading_numpy=True` parameter to `didjvu.gamera_support.init`, as you apparently call this method. This would keep the current implementation by default, but let a library user choose whether *numpy* should be disabled. Does this sound like a sufficient solution to you?

**Comment by jwilk** [comment]
I think you could restore `sys.modules` to the original state after Gamera is initialized.

**Comment by rmast** [comment]
Yes, done:
https://github.com/rmast/OCRmyPDF_DjVu_Optimize_Plugin/commit/44967482a0ae50388aa337a53832bbcb15f380bc
